### ISSUE TITLE
store.getMidnightMode doesn't get the new value

### ISSUE THREAD

**Issue by b0bdN** [b0bdN/prayer-times-menubar-app#1]
When I select the parameter MidnightMode in the settings panel and click on Apply, everything updates correctly.
But if I want to change later the value (without closing the app), the `store.getMidnightMode` variable does not change even though the value is updated with `store.setMidnightMode`.

See main.js:
```js
    // MidnightMode
    const midnightMode = args[15]
    console.log(midnightMode + ' store.getMidnightMode = ' + store.getMidnightMode)
    if (midnightMode !== store.getMidnightMode) {
      changed = true
      console.log('Storage: the parameter midnightMode is different.')
      store.setMidnightMode(midnightMode)
    }
```

Here is an extract from the terminal for the line _console.log(midnightMode + ' store.getMidnightMode = ' + store.getMidnightMode)_:
- when I choose _Mid Sunset to Fajr_
```
Apply button clicked.
1 store.getMidnightMode = 0
Storage: the parameter midnightMode is different.
...
```
- change of mind, I prefer the other parameter (_Mid Sunset to Sunrise_):
```
Apply button clicked.
0 store.getMidnightMode = 0
```

`store.getMidnightMode` stay to `0` even though I just updated to `1` the first time

**Comment by tikenov** [comment]
Fixed this issue.
The problem was that all get parameters returned variables but should be functions.
Also replaced setTimeout with await on fetching data.

**Comment by b0bdN** [comment]
Hi! Thank you for your time! :)
I'm new to JavaScript and the syntax async/await is not something I understand completely..
But your answer and modifications are a great help.

**Comment by tikenov** [comment]
Hi, actually this is my first contribution ever🙂 Hope it was helpful. found by label "good first issue".
