### ISSUE TITLE
check if there is a comma in the input City, Country

### ISSUE THREAD

**Issue by b0bdN** [b0bdN/prayer-times-menubar-app#5]
https://github.com/b0bdN/prayer-times-menubar-app/blob/15074588857dacaefe949cbc30705014df91b53c/main.js#L234

We need to check if there is a comma (,) in the input for the _City, Country_ when the user enter manually the information.

I think of two options:

1. the comma is mandatory, so we need to create a [`dialog`](https://www.electronjs.org/docs/latest/api/dialog) box to show the error.
2. it's ok to have just a space between _CITY_ and _COUNTRY_

**Comment by longtongj28** [comment]
Hello, can you assign this to me?

**Comment by b0bdN** [comment]
Hi!, thanks for your interest!
Of course you can work on this :)

What do you think will be best, should the comma be mandatory?

**Comment by longtongj28** [comment]
Some cities can be multiple words right? We should keep the comma mandatory

**Comment by longtongj28** [comment]
I am new to electron. Could you show me where in your code to create a dialog box in your to show the error? I have the logic that handles if the input is valid.

**Comment by b0bdN** [comment]
No worries ;)
I think it will be better to check the input in the [renderer process](https://github.com/b0bdN/prayer-times-menubar-app/blob/master/renderer.js) when the user click on the _Apply_ button before sending all the values to the Main process.
https://github.com/b0bdN/prayer-times-menubar-app/blob/06db1671277492d48a40d719682de747b8de5d77/renderer.js#L228

[`dialog`](https://www.electronjs.org/docs/latest/api/dialog) work only in the Main process, so you need to create an [Inter-process communication (IPC)](https://www.electronjs.org/docs/latest/tutorial/ipc#pattern-1-renderer-to-main-one-way) between the Renderer and the Main.
You can use `window.api.send('custom-channel', arg)`, add `custom-channel` in [preload.js](https://github.com/b0bdN/prayer-times-menubar-app/blob/master/preload.js) and listen in main.js with `ipcMain.on('custom-channel', () => {dialog...}`
