### ISSUE TITLE
Customizing increments arrow `input[type=number]`

### ISSUE THREAD

**Issue by b0bdN** [b0bdN/prayer-times-menubar-app#6]
It would be nice to customize the arrows for the `input[type=number]`.

![prayer-times-arrow](https://user-images.githubusercontent.com/23734573/155035618-093c2ef5-eb59-4854-890a-62753d671c1c.png)

**Comment by b0bdN** [comment]
We should not forget the arrows for the custom angles.

![prayer-times-arrow-angles](https://user-images.githubusercontent.com/23734573/155897288-7cd0a0dd-8929-4384-95ba-ddcc5225b803.png)

**Comment by b0bdN** [comment]
Hi! 
Thank you for your interest!
With pleasure :)

**Comment by Anthony-one** [comment]
Am i suppose to modify the javascript or just the css file?

**Comment by b0bdN** [comment]
It really depends of the style you want to implement.
Do you have a one in mind?

Some prefer to use exclusively CSS, others add JavaScript. It's up to you :)

**Comment by Anthony-one** [comment]
I might have misunderstood the task but do I have to design the arrows myself ? If not can I use a image I found online ?

**Comment by b0bdN** [comment]
I created this issue because I don't like how the arrows are represented.
I'd like to see something more like that:
![image](https://user-images.githubusercontent.com/23734573/158069454-68b677c7-6a82-4d04-91b0-e29cd84257fa.png)

Or like that:
https://www.cssscript.com/demo/number-spinner-quantity-input/
But I don't think there is room in the _Manual times adjustments_ section.

If you use an image found online you have the right to use it (with credit or not).
You can use the icons from Remix Icon: https://remixicon.com/

**Comment by Anthony-one** [comment]
Hi let me know what you think, i end up not replacing with an image because it would have lost the clickity feeling of it so i end up just reformating it so there is no blank space #10

**Comment by Anthony-one** [comment]
![Capture d’écran 2022-03-13 202211](https://user-images.githubusercontent.com/55881971/158075625-42be5a60-b92c-46d5-a19b-80c0753373c2.png)
So it looks like that
